[project]
name = "pdf-bm-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.16.0",
    "pymupdf>=1.26.5",
    "pyside6>=6.10.0",
]
